services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    volumes:
      - monitor-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - monitor
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "9600:9600"
      - "2424:2424"
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    depends_on:
      - elasticsearch
    networks:
      - monitor
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - monitor
networks:
  monitor:
    driver: bridge
volumes:
  monitor-elasticsearch:
    driver: local
