metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  protocol: "http"
  username: "elastic"
  password: "password"

setup.kibana:
  host: "http://kibana:5601"

metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - memory
      - diskio
      - filesystem
      - network
      - process
    enabled: true
    period: 10s
    processes: [".*"]

  - module: docker
    metricsets:
      - container
      - cpu
      - memory
      - network
      - diskio
    hosts: ["unix:///var/run/docker.sock"]
    enabled: true
    period: 10s
